### ISSUE TITLE
Status not update in Github when credentials changed

### ISSUE THREAD

**Issue by VictorLHS** [gocd-contrib/gocd-build-status-notifier#135]
Hi.

I'm experiencing an issue with the status notifier. We updated the user and the personal token with a different one and there is no communication at all with GitHub.

I got this error:
"textPayload: "jvm 1    | 2020-10-26 00:58:11,421 ERROR [159@MessageListener for PluginNotificationMessageListener] p.g.p.s.c.t.g.p.BuildStatusNotifierPlugin:127 [plugin-github.pr.status] - Error occurred. Could not update build status - URL: git@github.com:some-company/some-repo.git Revision: 22733ddfbced2dbb85a7e671d669814c18116572 Build: property-service_PR/481/unit-test/1 Result: Unknown"

Anyone experience something similar and solved it?

Cheers.

**Comment by chadlwilson** [comment]
Assume this is stale now. Can re-open if people see similar issues.
