### ISSUE TITLE
Github build status for downstream Pipelines

### ISSUE THREAD

**Issue by RabeaAfifi** [gocd-contrib/gocd-build-status-notifier#197]
Hi,

I have a multiple pipeline setup (mainly because I need to use templates).

So I have a main upstream pipeline that uses the SCM directly and for that pipeline I do see the status on github.
but for all other downstream pipelines which use the upstream pipeline as a material and NOT the SCM directly I don't see any status updates (they are not listed) on github.

is there a way to see all downstream pipelines ?

I am using version 1.7.1-169 of this plugin

**Comment by chadlwilson** [comment]
With the way this currently works, and the way the plugin APIs are designed within GoCD I don't think that is possible, no - see https://groups.google.com/g/go-cd/c/iKaEfamf3gM/m/GJibdVm9AwAJ for a similar question

**Comment by RabeaAfifi** [comment]
Then i have no use for pipeline templates as I must put all the flow in one
pipeline.

sorry for going off topic
But is there something similar to pipeline templates but for jobs,
I want to run some build jobs in parallel with the same tasks but each job
will use a different makefile.

I am trying not to duplicate the same 5 tasks for each build job.

**Comment by chadlwilson** [comment]
I'm not sure I understand  what you are trying to achieve. Probably better to write to the generic forums and get others' perspectives. Keep in mind that feature branch / PR flow has never been an emphasis for complex pipeline chains in GoCD, which is relatively opinionated (see [here](https://www.gocd.org/2015/04/27/Feature-Branch-Support.html) - plugins it mentions are old, but the philosophy it discusses are relevant).

Nevertheless, if your goal is to re-use logic or simplify maintainance of different building blocks of pipelines, (including stages/jobs) you are best to look at one of the pipelines-as-code plugins: https://docs.gocd.org/current/advanced_usage/pipelines_as_code.html

If you use the Yaml one, there is some re-use possible via YAML anchors, however the very nature of having the whole pipeline definition defined in code/yaml makes it easier to manage duplication than via UI clicky-clicky definitions.

If you use [the groovy plugin](https://github.com/gocd-contrib/gocd-groovy-dsl-config-plugin), you can extend this to full code re-use, and also use it to automatically generate separate pipelines for PRs when raised, if that is your flow.

**Comment by RabeaAfifi** [comment]
Thanks a lot!
I will look at the options you gave me here and open a discussion in the
correct forum if needed.
