### ISSUE TITLE
Cannot verify download .jar

### ISSUE THREAD

**Issue by thomasf1234** [gocd-contrib/gocd-build-status-notifier#33]
Hi. Can sha256 digests please be provided to ensure and verify the secure downloading of the .jar files listed on the releases page? specifically github-pr-status-1.3.jar. (https://github.com/gocd-contrib/gocd-build-status-notifier/releases/download/1.3/github-pr-status-1.3.jar)

**Comment by ketan** [comment]
We've added checksums starting from version 1.4 and will continue to do so.
