### ISSUE TITLE
check connection failed. Server returned HTTP response code: 401

### ISSUE THREAD

**Issue by hchemanchula** [gocd-contrib/gocd-build-status-notifier#38]
Hi,

I am using latest version of this plugin and not able to connect to the github repository while checking the connectivity from my pipeline. Can you please help?

Error:
`check connection failed. Server returned HTTP response code: 401 for URL: https://api.github.com/repos/***`

Thanks,
Hemanth

**Comment by Deepankar01** [comment]
yes it is happening same what is the issue
