### ISSUE TITLE
[Enhancement] Provide an option to rerun the build from PR

### ISSUE THREAD

**Issue by ajitsing** [gocd-contrib/gocd-build-status-notifier#39]
Would it be possible to provide an option to retrigger the pipeline irrespective of last build status?

My Use case: I have used this plugin to check the status of a few pipelines before merging a PR. I achieved this by creating a new pipeline which checks the status of dependent pipelines. The check runs once and based on the status it will allow or block merging of PR.

If I want to check the status of pipelines before merging then I will have to again rerun the status check to make sure the dependent pipelines are green. If we can add an option to rerun the pipeline from Github PR UI, it would be really great.

**Comment by ketan** [comment]
I don't believe this would be possible. The status check links need to point to a URL resource that is the target of a build. Opening that url and trigger a build, when in fact you wanted to see the status would be unexpected behavior.

Closing.
