### ISSUE TITLE
Wrong version displayed

### ISSUE THREAD

**Issue by riker09** [gocd-contrib/gocd-build-status-notifier#42]
This got me confused. I've downloaded the version 1.4 jar file from the releases tab and put it into the GoCD plugin folder. The plugin shows up once I restart my GoCD server, but the version that is displayed in the overview is `1.3`. The version of the jar file is 1.4, though.

![auswahl_001](https://user-images.githubusercontent.com/568497/53027399-22b2df80-3465-11e9-81ed-851989299f9c.png)

**Comment by arvindsv** [comment]
@riker09 Thanks for bringing this up!

[Release 1.5](https://github.com/gocd-contrib/gocd-build-status-notifier/releases/tag/1.5) (which is the same as 1.4, but with the version corrected) is now released.

**Comment by ketan** [comment]
I'll update the 1.4 releases page to warn about this bug.
