### ISSUE TITLE
Plugin versions are all set to stash.pr.status

### ISSUE THREAD

**Issue by ckaushik** [gocd-contrib/gocd-build-status-notifier#66]
Building any plugin from this repo seems to copy plugin id and description from Stash PR plugin

![image](https://user-images.githubusercontent.com/513388/58001669-c9a52700-7af9-11e9-869a-41b6b36c4991.png)

Steps to reproduce:

Build the project
`docker run --rm -v "$PWD":/home/gradle/project -w /home/gradle/project gradle gradle clean build`

Check the plugin.xml
`cat gitlab-mr-status/build/resources/main/plugin.xml`

**Comment by ckaushik** [comment]
cc @bdpiparva

**Comment by bdpiparva** [comment]
Fixed in https://github.com/gocd-contrib/gocd-build-status-notifier/releases/tag/1.6-73
