### ISSUE TITLE
Configurable Gerrit notification labels

### ISSUE THREAD

**Issue by jozefs** [gocd-contrib/gocd-build-status-notifier#7]
The plugin is setting the Code-Review label to +1 or -1, depending on whether a stage passed or failed. A more usual practice in Gerrit is to use the Verified label for this purpose. It is disabled by default in newer versions of Gerrit but it can be easily be enabled:

https://gerrit-review.googlesource.com/Documentation/config-labels.html#label_Verified

Would you consider making the voting label configurable or perhaps even switch the default to Verified?

**Comment by palvarez89** [comment]
+1

**Comment by gunnarx** [comment]
Yes, please.  Keeping actual code reviews separate from CI system report.  They are different things.

**Comment by ketan** [comment]
Closing via #16
