### ISSUE TITLE
GitHub Enterprise having issues

### ISSUE THREAD

**Issue by mkum9469** [gocd-contrib/gocd-build-status-notifier#74]
I have the `~/.github` file with `endpoint` defined. But I'm not getting any build status notifications to my PR. When I check the plugin logs I see the following errors. 

![Screenshot from 2019-08-02 16-54-00](https://user-images.githubusercontent.com/26281978/62441138-9d9c5800-b770-11e9-8854-d61eb570da8d.png)

**Comment by mkum9469** [comment]
@srinivasupadhya @juhasipo Any idea?

**Comment by gabyfulchic** [comment]
Did you try with the gocd 1.21 release and using the new plugin release ?
If it still not works, copy paste your plugin configuration if it continues to help us debbugging
Your /var/go/.github too if possible (hiding secret sure) :+1: 

If you use gocd with Github Enterprise, and you see the error with 401 unauthorized on api.github.com, it might indicate you mess a endpoint parameter somewhere I guess. On the plugin config or in the .github dotfile maybe.
