### ISSUE TITLE
README could be clearer about repo permission required

### ISSUE THREAD

**Issue by mrmanc** [gocd-contrib/gocd-build-status-notifier#93]
[This line in the readme](https://github.com/gocd-contrib/gocd-build-status-notifier/commit/83fcea5785511baed3a64770be0ffb5e7e6ee9ba#diff-04c6e90faac2675aa89e2176d2eec7d8R29) states that the username should be configured with:

> A Github user with push access to the repository.

While the user does require push access to the repository, this gives the impression that the plugin requires credentials with push access, which is not the case. The plugin works with a personal access token which has only the `repo:status` scope configured. It feels mildly safer to configure this amount of access given that this user ends up getting added as a collaborator for any repositories which want to build pull requests.

Would people be open to a PR which clarifies the access requires?

**Comment by ketan** [comment]
A PR would be much appreciated.

Thanks

- Ketan
