### ISSUE TITLE
Use Github ssh key 

### ISSUE THREAD

**Issue by chethanuk-plutoflume** [gocd-contrib/gocd-build-status-notifier#95]
Can we use [Github SSH key](https://github.com/gocd-contrib/gocd-build-status-notifier#github)?

**Comment by chadlwilson** [comment]
SSH keys can only be used to do native Git operations on repositories, not to talk to the API as required for these notifications. This project uses https://github.com/hub4j/github-api which supports OAuth/personal access token.
